# Generated by Django 3.1.2 on 2022-05-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_vendorpayments_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayments',
            name='method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Paypal', 'Paypal')], default='Bank', max_length=15),
        ),
    ]
