# Generated by Django 3.1.2 on 2022-05-09 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_requested'),
        ('payments', '0003_vendorpayments_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpayments',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='vendorpayments',
            name='vendor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
