# Generated by Django 3.1.2 on 2022-05-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20220509_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorpayments',
            old_name='comments',
            new_name='comment',
        ),
    ]
