# Generated by Django 3.1.2 on 2022-05-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('-id',), 'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
