# Generated by Django 3.1.2 on 2022-05-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220507_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='PagesList',
        ),
        migrations.AlterModelOptions(
            name='pageslist',
            options={'ordering': ('-id',), 'verbose_name': 'Pages List', 'verbose_name_plural': 'Pages List'},
        ),
    ]
