# Generated by Django 3.1.2 on 2022-05-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220507_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageslist',
            old_name='page_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pageslist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pageslist',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pageslist',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slugfiy'),
        ),
    ]
