# Generated by Django 3.1.2 on 2022-05-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pageslist_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageslist',
            options={'ordering': ('id',), 'verbose_name': 'Pages List', 'verbose_name_plural': 'Pages List'},
        ),
    ]
