# Generated by Django 3.1.2 on 2022-05-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages_List',
            new_name='MessagesList',
        ),
    ]
