# Generated by Django 3.1.2 on 2022-05-06 02:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220506_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslist',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
