# Generated by Django 3.1.2 on 2022-05-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220506_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslist',
            name='message',
            field=models.TextField(),
        ),
    ]
