# Generated by Django 3.1.2 on 2022-05-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bankaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='consultant_profile',
            new_name='vendor_profile',
        ),
    ]
