# Generated by Django 3.1.2 on 2022-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='admission'),
        ),
    ]
