# Generated by Django 3.1.2 on 2022-05-05 16:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publisher',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
