# Generated by Django 3.1.2 on 2022-05-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220429_0555'),
        ('blog', '0004_auto_20220505_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
