# Generated by Django 3.1.2 on 2022-05-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publisher',
            new_name='profile',
        ),
    ]
