# Generated by Django 3.1.2 on 2022-05-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_contactinfo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
