# Generated by Django 3.1.2 on 2022-05-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_contactinfo_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150)),
                ('Work_time', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Support Number',
                'verbose_name_plural': 'Support Numbers',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
