# Generated by Django 3.1.2 on 2022-05-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20220507_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, verbose_name='Site Name')),
                ('site_title', models.CharField(max_length=500, verbose_name='Site Title')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('site_logo', models.ImageField(blank=True, help_text="Please use our recommended dimensions: width='215' height='66'", max_length=1000, null=True, upload_to='site_logo/imgs/', verbose_name='Site Logo')),
                ('favicon', models.ImageField(blank=True, help_text="Please use our recommended dimensions: width='78' height='60'", max_length=1000, null=True, upload_to='site_logo/imgs/', verbose_name='Site favicon')),
                ('login_image', models.ImageField(blank=True, help_text="Please use our recommended dimensions: width='768' height='901'", max_length=1000, null=True, upload_to='site_logo/imgs/', verbose_name='Login screen')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ('id',),
            },
        ),
    ]
