# Generated by Django 3.1.2 on 2022-05-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_url',
            field=models.URLField(blank=True, null=True, verbose_name='Site URL'),
        ),
    ]
