# Generated by Django 3.1.2 on 2022-05-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20220507_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='STRIPESetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_public_key', models.CharField(max_length=150, verbose_name='Stripe Public Key')),
                ('stripe_secret_key', models.CharField(max_length=500, verbose_name='Stripe Secret Key')),
                ('stripe_webhook_secret', models.CharField(max_length=500, verbose_name='Stripe Webhook Secret ')),
                ('domain', models.URLField(blank=True, null=True, verbose_name='Your Domain')),
            ],
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Site Description'),
        ),
    ]
