# Generated by Django 3.1.2 on 2022-05-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20220509_0857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STRIPESetting',
        ),
    ]
