# Generated by Django 3.1.2 on 2022-05-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_delete_stripesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Site Description'),
        ),
    ]
