# Generated by Django 3.1.2 on 2022-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_sitesetting_footer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='shipping',
            field=models.FloatField(blank=True, null=True, verbose_name='Shipping fee'),
        ),
    ]
