# Generated by Django 3.1.2 on 2022-08-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_sitesetting_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=150, verbose_name='Page Name')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Home Page Theme',
                'verbose_name_plural': 'Home Pages Theme ',
                'ordering': ('id',),
            },
        ),
    ]
