# Generated by Django 3.1.2 on 2022-05-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220505_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreport',
            name='cpm',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='revenues',
        ),
    ]
