# Generated by Django 3.2.12 on 2022-02-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20220203_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='main_category',
            new_name='super_category',
        ),
    ]
