# Generated by Django 3.2.12 on 2022-02-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_rename_main_category_maincategory_super_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supercategory',
            old_name='date_created',
            new_name='date',
        ),
        migrations.AddField(
            model_name='supercategory',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slugfiy'),
        ),
    ]
