# Generated by Django 3.2.12 on 2022-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20220207_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='Slugfiy'),
        ),
    ]
