# Generated by Django 3.2.12 on 2022-02-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_supercategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slugfiy'),
        ),
    ]
