# Generated by Django 3.2.12 on 2022-02-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_supercategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='minicategory',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='date_created',
            new_name='date',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slugfiy'),
        ),
        migrations.AddField(
            model_name='minicategory',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='minicategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slugfiy'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slugfiy'),
        ),
    ]
