# Generated by Django 3.2.12 on 2022-02-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20220207_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=' categories/main/imgs/', verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='minicategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=' categories/mini/imgs/', verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=' categories/sub/imgs/', verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=' categories/super/imgs/', verbose_name='Category Image'),
        ),
    ]
