# Generated by Django 3.2.12 on 2022-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_auto_20220216_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='product_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Product Count'),
        ),
    ]
