# Generated by Django 3.2.12 on 2022-02-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_supercategory_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supercategory',
            name='product_count',
        ),
    ]
