# Generated by Django 3.2.12 on 2022-02-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_remove_supercategory_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.supercategory'),
        ),
    ]
