# Generated by Django 3.2.12 on 2022-02-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CARImage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 1920px x 728px, 250 KB MAX', null=True, upload_to='carousel/', verbose_name='Image')),
                ('CARtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('CARURL', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
