# Generated by Django 3.2.12 on 2022-02-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADS',
            new_name='HomeAds',
        ),
    ]
