# Generated by Django 3.2.12 on 2022-02-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_ads_homeads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeAds',
            new_name='HomeAd',
        ),
    ]
