# Generated by Django 3.2.12 on 2022-02-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_homeads_homead'),
    ]

    operations = [
        migrations.AddField(
            model_name='homead',
            name='image_position',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=13),
        ),
    ]
