# Generated by Django 3.2.12 on 2022-02-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_carousel_carimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeAd',
            new_name='HomeAdSidebar',
        ),
    ]
