# Generated by Django 3.2.12 on 2022-02-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220217_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeadmiddlesmall',
            name='ad_URL',
            field=models.URLField(blank=True, null=True, verbose_name='Supplier'),
        ),
    ]
