# Generated by Django 3.2.12 on 2022-02-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homeadmiddlesmall_ad_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeAdMiddleSmall',
            new_name='HomeAdSupplier',
        ),
    ]
