# Generated by Django 3.2.12 on 2022-02-18 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0014_auto_20220217_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdDealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 568px x 503px, 250 KB MAX', null=True, upload_to='ads/deal-time/', verbose_name='Image')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('ad_URL', models.URLField(blank=True, null=True, verbose_name='Product URL')),
                ('PRDdealtime', models.DateTimeField(blank=True, null=True, verbose_name='Deal Time')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Supplier')),
            ],
        ),
    ]
