# Generated by Django 3.2.12 on 2022-02-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homeaddealtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeaddealtime',
            name='PRDDiscountPrice',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='homeaddealtime',
            name='PRDPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
