# Generated by Django 3.2.12 on 2022-02-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220218_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaddealtime',
            name='PRDDiscountPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount'),
        ),
    ]
