# Generated by Django 3.2.12 on 2022-02-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homeaddealtime_prddiscountprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetailsAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 360px x 250px, 250 KB MAX', null=True, upload_to='ads/deal-time/', verbose_name='Image')),
                ('ad_URL', models.URLField(blank=True, null=True, verbose_name='Product URL')),
            ],
        ),
    ]
