# Generated by Django 3.2.12 on 2022-02-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_code'),
        ('home', '0018_vendordetailsadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetailsadimage',
            name='ad_mage',
            field=models.ImageField(blank=True, help_text='Please use our recommended dimensions: 360px x 250px, 250 KB MAX', null=True, upload_to='ads/vendor-page/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ShopAdSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 1024px x 1076px, 250 KB MAX', null=True, upload_to='ads/shop-ad/', verbose_name='Image')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('ad_URL', models.URLField(blank=True, null=True)),
                ('image_position', models.CharField(choices=[('Right', 'Right')], default='Right', max_length=13)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Supplier')),
            ],
        ),
    ]
