# Generated by Django 3.2.12 on 2022-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220222_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 508px x 332px, 250 KB MAX', null=True, upload_to='ads/hot-deal-ad/', verbose_name='Image')),
                ('rate', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Discount Percentage')),
                ('ad_URL', models.URLField(blank=True, null=True)),
                ('image_position', models.CharField(choices=[('Right', 'Right')], default='Right', max_length=13)),
            ],
        ),
    ]
