# Generated by Django 3.1.2 on 2022-05-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_headtextad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headtextad',
            name='ad_title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Title'),
        ),
    ]
