# Generated by Django 3.1.2 on 2022-05-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220506_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeaddealtime',
            name='supplier_URL',
            field=models.URLField(blank=True, null=True, verbose_name='supplier URL'),
        ),
    ]
