# Generated by Django 3.2.12 on 2022-02-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
