# Generated by Django 3.2.12 on 2022-03-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_client',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
