# Generated by Django 3.2.12 on 2022-03-10 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20220310_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
