# Generated by Django 3.2.12 on 2022-03-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_payment_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailssupplier',
            name='order_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ordersupplier'),
        ),
    ]
