# Generated by Django 3.2.12 on 2022-03-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_product_prdslug'),
        ('orders', '0014_orderdetailssupplier_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailssupplier',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderdetailssupplier',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
