# Generated by Django 3.2.12 on 2022-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_code'),
        ('orders', '0015_auto_20220318_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(related_name='vendors', to='accounts.Profile'),
        ),
    ]
