# Generated by Django 3.2.12 on 2022-03-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendors',
        ),
    ]
