# Generated by Django 3.2.12 on 2022-03-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersupplier',
            name='rpt_cache',
        ),
        migrations.RemoveField(
            model_name='ordersupplier',
            name='tracking_no',
        ),
        migrations.RemoveField(
            model_name='ordersupplier',
            name='weight',
        ),
    ]
