# Generated by Django 3.2.12 on 2022-03-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_code'),
        ('orders', '0018_auto_20220323_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersupplier',
            name='vendors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='accounts.profile'),
        ),
    ]
