# Generated by Django 3.2.12 on 2022-03-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_rename_vendors_ordersupplier_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersupplier',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
