# Generated by Django 3.2.12 on 2022-03-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_orderdetailssupplier_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_supplier',
        ),
    ]
