# Generated by Django 3.1.2 on 2022-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20220429_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auth_token_order',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id_paymob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trnx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
