# Generated by Django 3.2.12 on 2022-02-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20220203_0652'),
        ('products', '0002_auto_20220203_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_maincategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.maincategory', verbose_name='3.Main Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_minicategor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.minicategory', verbose_name='1.Mini Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory', verbose_name='4.Sub Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_supercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.supercategory', verbose_name='2.Super Category'),
        ),
    ]
