# Generated by Django 3.2.12 on 2022-02-04 03:17

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='PRDIImage',
            field=models.ImageField(upload_to=products.models.ProductImage.upload_file_name, verbose_name='Image'),
        ),
    ]
