# Generated by Django 3.2.12 on 2022-02-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_prdiimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='PRDIImage',
            field=models.ImageField(upload_to='products/imgs/product_imgs/', verbose_name='Image'),
        ),
    ]
