# Generated by Django 3.2.12 on 2022-02-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_prdiimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensions'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISHot',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Hot'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISNew',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='New'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISSale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDSKU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDWeight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='WEIGHT_KG'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDWeight_oz',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='WEIGHT_OZ'),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='piece_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Piece WEIGHT_GM'),
        ),
        migrations.AddField(
            model_name='product',
            name='piece_weight_oz',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Piece WEIGHT_OZ'),
        ),
        migrations.AddField(
            model_name='product',
            name='pieces',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='pieces/set'),
        ),
    ]
