# Generated by Django 3.2.12 on 2022-02-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220204_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDISHot',
            field=models.BooleanField(default=False, verbose_name='Hot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDISNew',
            field=models.BooleanField(default=True, verbose_name='New'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDISSale',
            field=models.BooleanField(default=False, verbose_name='Sale'),
        ),
    ]
