# Generated by Django 3.2.12 on 2022-02-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220204_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDWeight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='SET WEIGHT_KG'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDWeight_oz',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='SET WEIGHT_OZ'),
        ),
    ]
