# Generated by Django 3.2.12 on 2022-02-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220204_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDISactive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDtags',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tags'),
        ),
    ]
