# Generated by Django 3.2.12 on 2022-02-17 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_auto_20220217_0724'),
        ('products', '0024_alter_product_product_image_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_maincategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.maincategory', verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_minicategor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.minicategory', verbose_name='Mini Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_supercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.supercategory', verbose_name='Super Category'),
        ),
    ]
