# Generated by Django 3.2.12 on 2022-02-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_product_image_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_sale',
        ),
    ]
