# Generated by Django 3.2.12 on 2022-02-28 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_product_product_image_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='products/imgs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Product Image'),
        ),
    ]
