# Generated by Django 3.2.12 on 2022-03-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDISHot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDISNew',
        ),
        migrations.AddField(
            model_name='product',
            name='promotional',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Hot', 'Hot')], default='New', max_length=13, null=True),
        ),
    ]
