# Generated by Django 3.2.12 on 2022-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20220301_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Dimensions',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
