# Generated by Django 3.2.12 on 2022-03-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_product_prdisactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDWeight_oz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='piece_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='piece_weight_oz',
        ),
    ]
