# Generated by Django 3.2.12 on 2022-03-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_product_prdcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDISDeleted',
            field=models.BooleanField(default=False, verbose_name='Product Deleted'),
        ),
    ]
