# Generated by Django 3.2.12 on 2022-03-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='PRDIImage',
            field=models.ImageField(max_length=500, upload_to='products/imgs/product_imgs/', verbose_name='Image'),
        ),
    ]
