# Generated by Django 3.2.12 on 2022-03-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_productimage_prdiimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',)},
        ),
    ]
