# Generated by Django 3.2.12 on 2022-03-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(max_length=500, upload_to='products/imgs/', verbose_name='Product Image'),
        ),
    ]
