# Generated by Django 3.2.12 on 2022-03-02 13:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20220302_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Full Description'),
        ),
    ]
