# Generated by Django 3.1.2 on 2022-05-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220429_0555'),
        ('products', '0054_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='PRDIProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
    ]
