# Generated by Django 3.1.2 on 2022-05-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_auto_20220504_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feedbak_average',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Feedbak average'),
        ),
    ]
