# Generated by Django 3.1.2 on 2022-05-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_auto_20220504_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
