# Generated by Django 3.1.2 on 2022-05-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_auto_20220504_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='start_1'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='start_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='start_3'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='start_4'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='start_5'),
        ),
    ]
