# Generated by Django 3.1.2 on 2022-05-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_auto_20220505_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='start_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_5',
        ),
    ]
