# Generated by Django 3.2.14 on 2022-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_alter_productsize_name_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='name_variation',
            field=models.CharField(blank=True, help_text="Please enter only one of these values 'XXS ,XS , S , M , L , XL . XXL' ", max_length=100, null=True, verbose_name='Name Variation'),
        ),
    ]
